### ISSUE TITLE
How to perform PATCH

### ISSUE THREAD

**Issue by sundeep95** [DMTF/Redfish-Profile-Simulator#10]
Hello

How to perform patch operation on the service?
Can you please provide the procedure?

Thanks.

**Comment by mraineri** [comment]
Performing a PATCH operation on the service is just like any other HTTP service; you send an HTTP request with PATCH as the method, and the body contains the items you'd like to update. For example, if you want to change the state of IndicatorLED in a given ComputerSystem to "Lit", you can use this as the PATCH body:
`
{
    "IndicatorLED": "Lit"
}
`

The specifics about how to carry out the PATCH will vary based on your environment; there are browser plugins (like Postman for Chrome) that let you perform raw HTTP operations from your browser. You can also use Curl from the command line to issue a PATCH against a target URL.

**Comment by mraineri** [comment]
1/11: Closing
