### ISSUE TITLE
Failed to get the some resources under ComputerSystem from the Redfish-Profile-Simulator 

### ISSUE THREAD

**Issue by CShia** [DMTF/Redfish-Profile-Simulator#12]
Below is the code in the Redfish-Profile-Simulator\v1sim\systems.py, which is used to walk through the mockup folders under Systems in order to get the json files.

We can see some strings  which doesn’t match the properties under ComputerSystem in ComputerSystem.json: “bios” should be “Bios”, NetworkAdapters should be “NetworkInterfaces “,”PCIDevices” should be “PCIeDevices”. 

class RfSystemObj(RfResource):
    def create_sub_objects(self, base_path, rel_path):
        resource_path = os.path.join(base_path, rel_path)
        contents = os.listdir(resource_path)
        for item in contents:
            if item == "bios":
                self.components[item] = RfBios(base_path, os.path.join(rel_path, item), parent=self)
            elif item == "EthernetInterfaces":
                self.components[item] = RfEthernetCollection(base_path, os.path.join(rel_path, item), parent=self)
            elif item == "LogServices":
                self.components[item] = RfLogServiceCollection(base_path, os.path.join(rel_path, item), parent=self)
            elif item == "Memory":
                self.components[item] = RfMemoryCollection(base_path, os.path.join(rel_path, item), parent=self)
            elif item == "Processors":
                self.components[item] = RfProcessorCollection(base_path, os.path.join(rel_path, item), parent=self)
            elif item == "SimpleStorage":
                self.components[item] = RfSimpleStorageCollection(base_path, os.path.join(rel_path, item), parent=self)
            elif item == "SmartStorage":
                self.components[item] = RfSmartStorage(base_path, os.path.join(rel_path, item), parent=self)
            elif item == "SecureBoot":
                self.components[item] = RfSecureBoot(base_path, os.path.join(rel_path, item), parent=self)
            elif item == "NetworkAdapters":
                self.components[item] = RfNetworkAdapterCollection(base_path, os.path.join(rel_path, item), parent=self)
            elif item == "PCIDevices":
                self.components[item] = RfPCIDeviceCollection(base_path, os.path.join(rel_path, item), parent=self)
            elif item == "PCISlots":
                self.components[item] = RfPCISlotCollection(base_path, os.path.join(rel_path, item), parent=self)
            elif item == "FirmwareInventory":
                self.components[item] = RfSystemFirmwareInventory(base_path, os.path.join(rel_path, item), parent=self)
            elif item == "USBDevices":
                self.components[item] = RfUSBDeviceCollection(base_path, os.path.join(rel_path, item), parent=self)
            elif item == "USBPorts":
                self.components[item] = RfUSBPortCollection(base_path, os.path.join(rel_path, item), parent=self)

**Comment by CShia** [comment]
I already have a fix. Will submit a pull request soon.

**Comment by mraineri** [comment]
Fixed via latest PR
