### ISSUE TITLE
RedfishExtensions instead of Redfish in index.html ?

### ISSUE THREAD

**Issue by frsauvage** [DMTF/Redfish-Profile-Simulator#25]
Hi,

I ran the Redfish Validator on the Redfish Simulator.

I had 2 error messages:

`In the resource $metadata, the RedfishExtensions.v1_0_0 namespace must have an alias of 'Redfish'. The alias is 'RedfishExtensions'. This may cause properties of the form [PropertyName]@Redfish.TermName to be unrecognized.`

And:

`No such reference Redfish in /redfish/v1/$metadata`

I changed the Alias from "RedfishExtensions" to "Redfish" as indicated
and now I have no error message

in file Redfish-Profile-Simulator/MockupData/SimpleOcpServerV1/redfish/v1/$metadata/index.xml

**=> isn't it a bug in $metadata/index.html page in the Simulator ?**

Regards,
Francine

**Comment by billdodd** [comment]
@frsauvage Yes, you are absolutely correct.

**Comment by frsauvage** [comment]
OK, thank you
